changed start container steps

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -98,13 +98,15 @@ stages:
         - checkout: self
 
         # Run container
+        - task: Docker@2
+          displayName: Login to ACR
+          inputs:
+            command: login
+            containerRegistry: prodacr001-manual
+
         - script: |
-            docker run --name ros-demo \
-              $(acrName)/$(imageName):$(imageTag) || true
-
-            docker ps -a
-          displayName: Start Container
-
+           docker pull $(acrName)/$(imageName):$(imageTag)
+           displayName: Pull Image
         # Show container status
         - script: |
             docker ps -a
@@ -117,25 +119,31 @@ stages:
 
         # Validate ROS2 output
         - script: |
-            docker logs ros-demo > output.log 2>&1 || true
-            cat output.log
+           echo "========== CONTAINERS =========="
+           docker ps -a
 
-            if grep -q "Hello, world!" output.log; then
-              echo "ROS2 publisher validation successful"
-            else
-              echo "ROS2 publisher validation failed"
-              exit 1
-            fi
-          displayName: Validate Publisher
+           echo "========== LOGS =========="
+           docker logs ros-demo || true
+
+           docker logs ros-demo > output.log 2>&1 || true
+           cat output.log
+
+           if grep -q "Hello, world!" output.log; then
+           echo "ROS2 publisher validation successful"
+           else
+           echo "ROS2 publisher validation failed"
+           exit 1
+           fi
+           displayName: Validate Publisher
 
         # Save logs as artifact
         - script: |
             docker logs ros-demo > publisher.log 2>&1 || true
-          displayName: Save Logs
+            displayName: Save Logs
 
-        - task: PublishBuildArtifacts@1
-          displayName: Publish Logs Artifact
-          inputs:
+            - task: PublishBuildArtifacts@1
+             displayName: Publish Logs Artifact
+             inputs:
             PathtoPublish: publisher.log
             ArtifactName: ros2-logs
 
